package server

import (
	"github.com/cockroachdb/cockroach/pkg/sql/sqlbase"
	"github.com/cockroachdb/cockroach/pkg/util/hlc"
)

const a = sqlbase.TableDescriptor{Name: "_",
	ID:        0x120,
	ParentID:  0x32,
	Version:   0x2,
	UpVersion: false,
	ModificationTime: hlc.Timestamp{WallTime: 1515744566902143700,
		Logical: 0},
	Columns: []sqlbase.ColumnDescriptor{{Name: "_",
		ID: 0x1,
		Type: sqlbase.ColumnType{SemanticType: 7,
			Width:           20,
			Precision:       0,
			ArrayDimensions: []int32(nil),
			Locale:          (*string)(nil),
			VisibleType:     0,
			ArrayContents:   (*sqlbase.ColumnType_SemanticType)(nil)},
		Nullable:    false,
		DefaultExpr: (*string)(nil),
		Hidden:      false},
		{Name: "_",
			ID: 0x2,
			Type: sqlbase.ColumnType{SemanticType: 7,
				Width:           20,
				Precision:       0,
				ArrayDimensions: []int32(nil),
				Locale:          (*string)(nil),
				VisibleType:     0,
				ArrayContents:   (*sqlbase.ColumnType_SemanticType)(nil)},
			Nullable:    true,
			DefaultExpr: (*string)(nil),
			Hidden:      false},
		{Name: "_",
			ID: 0x3,
			Type: sqlbase.ColumnType{SemanticType: 5,
				Width:           0,
				Precision:       0,
				ArrayDimensions: []int32(nil),
				Locale:          (*string)(nil),
				VisibleType:     0,
				ArrayContents:   (*sqlbase.ColumnType_SemanticType)(nil)},
			Nullable:    true,
			DefaultExpr: (*string)(nil),
			Hidden:      false},
		{Name: "_",
			ID: 0x4,
			Type: sqlbase.ColumnType{SemanticType: 1,
				Width:           0,
				Precision:       0,
				ArrayDimensions: []int32(nil),
				Locale:          (*string)(nil),
				VisibleType:     1,
				ArrayContents:   (*sqlbase.ColumnType_SemanticType)(nil)},
			Nullable:    true,
			DefaultExpr: (*string)(0xc4204e5d70),
			Hidden:      false}},
	NextColumnID: 0x5,
	Families: []sqlbase.ColumnFamilyDescriptor{{Name: "_",
		ID: 0x0,
		ColumnNames: []string{"_",
			"_",
			"_",
			"_"},
		ColumnIDs: []sqlbase.ColumnID{0x1,
			0x2,
			0x3,
			0x4},
		DefaultColumnID: 0x0}},
	NextFamilyID: 0x1,
	PrimaryIndex: sqlbase.IndexDescriptor{Name: "_",
		ID:                 0x1,
		Unique:             true,
		ColumnNames:        []string{"_"},
		ColumnDirections:   []sqlbase.IndexDescriptor_Direction{0},
		StoreColumnNames:   []string(nil),
		ColumnIDs:          []sqlbase.ColumnID{0x1},
		ExtraColumnIDs:     []sqlbase.ColumnID(nil),
		StoreColumnIDs:     []sqlbase.ColumnID(nil),
		CompositeColumnIDs: []sqlbase.ColumnID(nil),
		ForeignKey: sqlbase.ForeignKeyReference{Table: 0x0,
			Index:           0x0,
			Name:            "",
			Validity:        0,
			SharedPrefixLen: 0,
			OnDelete:        0,
			OnUpdate:        0},
		ReferencedBy:  []sqlbase.ForeignKeyReference(nil),
		Interleave:    sqlbase.InterleaveDescriptor{Ancestors: []sqlbase.InterleaveDescriptor_Ancestor(nil)},
		InterleavedBy: []sqlbase.ForeignKeyReference(nil),
		Partitioning: sqlbase.PartitioningDescriptor{NumColumns: 0x0,
			List:  []sqlbase.PartitioningDescriptor_List(nil),
			Range: []sqlbase.PartitioningDescriptor_Range(nil)}},
	Indexes:        []sqlbase.IndexDescriptor(nil),
	NextIndexID:    0x2,
	Privileges:     (*sqlbase.PrivilegeDescriptor)(0xc4204e61c0),
	Mutations:      []sqlbase.DescriptorMutation(nil),
	Lease:          (*sqlbase.TableDescriptor_SchemaChangeLease)(nil),
	NextMutationID: 0x1,
	FormatVersion:  0x3,
	State:          2,
	Checks:         []*sqlbase.TableDescriptor_CheckConstraint(nil),
	Renames:        []sqlbase.TableDescriptor_RenameInfo(nil),
	ViewQuery:      "",
	DependsOn:      []sqlbase.ID(nil),
	DependedOnBy:   []sqlbase.TableDescriptor_Reference(nil),
	MutationJobs:   []sqlbase.TableDescriptor_MutationJob(nil),
	SequenceOpts:   (*sqlbase.TableDescriptor_SequenceOpts)(nil)}
